'use client';

import { useMemo, useState } from 'react';
import { AlertCircle, ArrowDownRight, ArrowUpRight, BookOpen, Building2, ChevronDown, ChevronRight, CircleDollarSign, Download, ExternalLink, FileQuestion, Landmark, Menu, Search, Shield, Users, X } from 'lucide-react';
import records from '@/data/records.json';
import sources from '@/data/sources.json';

type RecordItem = (typeof records)[number];
type Section = 'Overview' | 'Money In' | 'Money Out' | 'People / Payroll' | 'Sheriff / Public Safety' | 'Stormwater' | 'Vendors & Contracts' | 'Capital Projects' | 'Debt & Reserves' | 'Year-over-Year' | 'Questions / Flags' | 'Sources';
const navSections: { label: Section; icon: typeof CircleDollarSign }[] = [
  { label: 'Overview', icon: CircleDollarSign }, { label: 'Money In', icon: ArrowDownRight }, { label: 'Money Out', icon: ArrowUpRight }, { label: 'People / Payroll', icon: Users }, { label: 'Sheriff / Public Safety', icon: Shield }, { label: 'Stormwater', icon: CircleDollarSign }, { label: 'Vendors & Contracts', icon: Building2 }, { label: 'Capital Projects', icon: Landmark }, { label: 'Debt & Reserves', icon: Landmark }, { label: 'Year-over-Year', icon: BookOpen }, { label: 'Questions / Flags', icon: FileQuestion }, { label: 'Sources', icon: BookOpen },
];
const money = (value: number | null, short = false) => value === null ? 'Not yet populated' : short && value >= 1_000_000 ? `$${(value / 1_000_000).toFixed(value % 1_000_000 ? 2 : 0)}M` : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const labels: Record<string,string> = { verified_official:'Verified official', official_estimate:'Official estimate', derived_estimate:'Derived calculation', rough_estimate:'Rough estimate', pending:'Not yet populated' };
function Status({value}:{value:string}) { return <span className={`status status-${value}`}>{labels[value]??value}</span> }
function EmptyState({title,text}:{title:string;text:string}) { return <div className="empty-state"><div className="empty-icon"><FileQuestion size={21}/></div><h3>{title}</h3><p>{text}</p></div> }

export default function Home() {
 const [section,setSection]=useState<Section>('Overview'), [mobileNav,setMobileNav]=useState(false), [fiscalYear,setFiscalYear]=useState('FY2025-26'), [query,setQuery]=useState(''), [department,setDepartment]=useState('All departments'), [category,setCategory]=useState('All categories'), [sourceStatus,setSourceStatus]=useState('All source statuses');
 const [expanded,setExpanded]=useState<Record<string,boolean>>({expense:true,revenue:true,'sheriff / public safety':true,'public works':true,stormwater:true,countywide:true});
 const departments=['All departments',...Array.from(new Set(records.map(r=>r.department)))], categories=['All categories',...Array.from(new Set(records.map(r=>r.category)))];
 const filtered=useMemo(()=>records.filter(r=>{const q=query.toLowerCase(); return r.fiscalYear===fiscalYear&&(!q||`${r.name} ${r.department} ${r.category}`.toLowerCase().includes(q))&&(department==='All departments'||r.department===department)&&(category==='All categories'||r.category===category)&&(sourceStatus==='All source statuses'||r.sourceStatus===sourceStatus)}),[fiscalYear,query,department,category,sourceStatus]);
 const verifiedBudget=records.find(r=>r.id==='all-funds-total')?.amount??0, estimateRevenue=records.find(r=>r.id==='stormwater-revenue')?.amount??0, commissionerBase=records.filter(r=>r.id.startsWith('commissioner-')).reduce((s,r)=>s+(r.amount??0),0);
 const setActive=(s:Section)=>{setSection(s);setMobileNav(false);window.scrollTo({top:0,behavior:'smooth'})};
 const filters={query,setQuery,department,setDepartment,category,setCategory,sourceStatus,setSourceStatus,departments,categories};
 return <div className="app-shell">
  <aside className={`sidebar ${mobileNav?'sidebar-open':''}`}><div className="brand"><div className="brand-mark"><Landmark size={20}/></div><div><strong>Money Trail</strong><span>Clay County, Florida</span></div></div><button className="mobile-close" onClick={()=>setMobileNav(false)} aria-label="Close menu"><X/></button><nav>{navSections.map(({label,icon:Icon})=><button key={label} className={section===label?'active':''} onClick={()=>setActive(label)}><Icon size={17}/><span>{label}</span>{label==='Questions / Flags'&&<b>4</b>}</button>)}</nav><div className="sidebar-note"><span>DATA COVERAGE</span><strong>Early build</strong><div><i style={{width:'18%'}}/></div><p>Verified records will replace empty branches as they are collected.</p></div></aside>
  {mobileNav&&<button className="scrim" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}
  <main><header className="topbar"><button className="menu-button" onClick={()=>setMobileNav(true)} aria-label="Open menu"><Menu/></button><div><span className="eyebrow">PUBLIC BUDGET EXPLORER</span><h1>{section}</h1></div><label className="fy-pill"><span>Fiscal year</span><select value={fiscalYear} onChange={e=>setFiscalYear(e.target.value)} aria-label="Fiscal year"><option value="FY2024-25">FY 2024–25</option><option value="FY2025-26">FY 2025–26</option><option value="FY2026-27">FY 2026–27</option></select><ChevronDown size={14}/></label></header><div className="content">
  {section==='Overview'&&<><div className="intro-row"><div><h2>Follow the public dollar.</h2><p>Explore verified Clay County budget figures, official estimates, and the gaps that still need answers.</p></div><span className="updated">Growing dataset · {records.length} records</span></div><Disclaimer/><div className="kpi-grid">
   <Kpi icon={<ArrowUpRight/>} color="blue" label="Total all-funds budget" value={money(verifiedBudget,true)} note="Appropriated · not actual spending"/><Kpi icon={<ArrowDownRight/>} color="teal" label="Stormwater revenue" value={money(estimateRevenue,true)} note="Official estimate"/><Kpi icon={<Users/>} color="gold" label="Commissioner base pay" value={money(commissionerBase,true)} note="5 × $37,000 per charter"/><Kpi icon={<FileQuestion/>} color="gray" label="Actual spending" value="Not yet populated" note="Awaiting expenditure records" muted/>
  </div><div className="overview-grid"><section className="panel"><div className="panel-head"><div><span className="section-kicker">ALL-FUNDS FUNCTIONAL MAP</span><h3>Where the verified budget goes</h3></div><button onClick={()=>setActive('Money Out')}>Explore all <ChevronRight size={15}/></button></div><div className="treemap"><button className="tile sheriff" onClick={()=>setActive('Sheriff / Public Safety')}><span>PUBLIC SAFETY</span><strong>$228.33M</strong><small>Budgeted</small></button><button className="tile detention" onClick={()=>setActive('Money Out')}><span>GENERAL GOVERNMENT</span><strong>$114.60M</strong><small>Budgeted</small></button><button className="tile works" onClick={()=>setActive('Money Out')}><span>TRANSPORTATION</span><strong>$80.35M</strong><small>Budgeted</small></button><button className="tile traffic" onClick={()=>setActive('Money Out')}><span>PHYSICAL ENVIRONMENT</span><strong>$45.90M</strong></button><button className="tile signs" onClick={()=>setActive('Money Out')}><span>HUMAN SERVICES</span><strong>$32.42M</strong></button></div><div className="legend"><span><i className="legend-blue"/>All funds</span><span><i className="legend-teal"/>FY2025–26</span><span>Functional expenditures exclude transfers and ending balances</span></div></section>
  <section className="panel questions"><div className="panel-head"><div><span className="section-kicker">OPEN QUESTIONS</span><h3>What still needs answers</h3></div><button onClick={()=>setActive('Questions / Flags')}>View all <ChevronRight size={15}/></button></div>{[['Actual vs. budgeted spending','Countywide actual expenditures are not loaded yet.'],['Complete employee compensation','Salary, overtime, benefits, and retirement remain incomplete.'],['Stormwater project allocation','How will the estimated net revenue reach specific projects?'],['Vendor and contract payments','No verified vendor-level payments are loaded yet.']].map(([t,d],i)=><button className="question-row" key={t} onClick={()=>setActive('Questions / Flags')}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{t}</strong><small>{d}</small></div><ChevronRight size={16}/></button>)}</section></div><section className="panel recent"><div className="panel-head"><div><span className="section-kicker">VERIFIED RECORDS</span><h3>Initial source-backed figures</h3></div><button onClick={()=>setActive('Sources')}>Review sources <ExternalLink size={14}/></button></div><RecordsTable records={records.filter(r=>r.amount!==null).slice(0,6)}/></section></>}
  {(section==='Money In'||section==='Money Out')&&<Explorer kind={section==='Money In'?'revenue':'expense'} records={filtered} expanded={expanded} setExpanded={setExpanded} filters={filters}/>} 
  {section==='People / Payroll'&&<StandardPage kicker="PEOPLE & COMPENSATION" title="What does Clay County government cost to staff?" description="Base salary is only one part of compensation. Overtime, benefits, retirement, allowances, and total taxpayer cost remain separate fields."><Disclaimer title="Aggregate budgets, not named employee pay." text="Commissioner entries are charter base salaries. CCSO calculations combine official division totals; they do not estimate compensation for any named employee."/><div className="method-strip"><div><span>VERIFIED</span><strong>Reported by an official source</strong></div><div><span>DERIVED</span><strong>Arithmetic from verified figures</strong></div><div><span>ROUGH ESTIMATE</span><strong>Assumption and range required</strong></div></div><FilterBar {...filters}/><section className="panel"><RecordsTable records={filtered.filter(r=>r.domain==='people'||(r.domain==='calculation'&&(r.category==='Payroll'||r.category==='Personnel')))}/></section></StandardPage>}
  {section==='Sheriff / Public Safety'&&<StandardPage kicker="PUBLIC SAFETY" title="Sheriff and detention budget trail" description="The Sheriff’s approved presentation and the County’s fund/cost-center budget are preserved as separate accounting views."><div className="feature-total"><div><span>CCSO APPROVED PRESENTATION · FY2025–26</span><strong>{money(109_359_102)}</strong><small>Law enforcement + detention + judicial + building maintenance + legal advertising</small></div><Shield/></div><Disclaimer title="Reconciliation required." text="CCSO’s presentation and the County’s budget use different fund and cost-center structures. Do not add their totals together; the dashboard preserves both until every transfer and allocation is reconciled."/><section className="panel"><RecordsTable records={records.filter(r=>(r.sourceId==='ccso-approved-budget'||r.department==='Sheriff / Public Safety')&&r.fiscalYear===fiscalYear)}/></section></StandardPage>}
  {section==='Stormwater'&&<StandardPage kicker="SPECIAL ASSESSMENT" title="Stormwater money trail" description="Track the proposed assessment from estimated collections through regulatory costs and, later, actual projects and payments."><div className="flow-cards"><div><span>Estimated assessment revenue</span><strong>$8,218,308</strong><Status value="official_estimate"/></div><ChevronRight/><div><span>First-year regulatory / collection costs</span><strong>$624,371</strong><Status value="official_estimate"/></div><ChevronRight/><div className="net"><span>Estimated remainder*</span><strong>$7,593,937</strong><small>*Arithmetic difference, not a verified allocation</small></div></div><section className="panel"><RecordsTable records={records.filter(r=>r.department==='Stormwater'&&r.fiscalYear===fiscalYear)}/></section></StandardPage>}
  {section==='Vendors & Contracts'&&<StandardPage kicker="DATASET READY" title={section} description="The schema is ready for official records, but no verified vendor-level payments have been loaded."><EmptyState title="Not yet populated" text="No number is shown until it can be tied to an official source and labeled as budgeted, amended, estimated, or actual."/></StandardPage>}
  {section==='Capital Projects'&&<StandardPage kicker="CAPITAL APPROPRIATIONS" title="Capital Projects" description="Fund-level appropriations are now loaded. Individual projects, amendments, contracts, and actual payments remain to be imported."><section className="panel"><RecordsTable records={records.filter(r=>r.domain==='capital'&&r.fiscalYear===fiscalYear)}/></section></StandardPage>}
  {section==='Debt & Reserves'&&<StandardPage kicker="DEBT & ENDING BALANCES" title="Debt & Reserves" description="Budgeted debt-service funds and General Fund ending balances are shown separately from actual payments and unrestricted cash."><section className="panel"><RecordsTable records={records.filter(r=>(r.domain==='debt'||r.domain==='reserves')&&r.fiscalYear===fiscalYear)}/></section></StandardPage>}
  {section==='Year-over-Year'&&<StandardPage kicker="FY2021–FY2027" title="Year-over-year comparison" description="Sheriff division comparisons now cover two approved budgets. Other years and actuals remain open data work."><div className="year-strip">{['FY2021','FY2022','FY2023','FY2024','FY2025','FY2026','FY2027'].map(y=><div key={y} className={y==='FY2026'?'current':''}><span>{y}</span><strong>{y==='FY2025'||y==='FY2026'?'Partial data':'Not populated'}</strong></div>)}</div><section className="panel"><RecordsTable records={records.filter(r=>r.category==='Sheriff Detail'&&(r.fiscalYear==='FY2024-25'||r.fiscalYear==='FY2025-26'))}/></section></StandardPage>}
  {section==='Questions / Flags'&&<StandardPage kicker="ACCOUNTABILITY QUEUE" title="Questions that records should answer" description="A transparent list of known data gaps—questions, not conclusions."><div className="flag-grid">{[['Actual vs. budgeted','What was actually paid in FY2025–26, by fund and cost center?'],['Payroll completeness','What are base pay, overtime, benefits, retirement, and total compensation for each employee?'],['Stormwater allocation','Which projects, contractors, and administrative costs receive assessment revenue?'],['Vendor payments','Who are the top vendors, and which awards were competitively bid?'],['Double-counting risk','Which cost centers appear across multiple funds or summaries?'],['Countywide totals','What is the reconciled, all-funds total for every functional category?']].map(([t,d],i)=><article className="flag-card" key={t}><span>QUESTION {String(i+1).padStart(2,'0')}</span><h3>{t}</h3><p>{d}</p><small>Open · Source needed</small></article>)}</div></StandardPage>}
  {section==='Sources'&&<StandardPage kicker="SOURCE REGISTER" title="Every number should be traceable" description="Official source links, record status, and notes for the initial dataset."><section className="panel source-list">{sources.map(s=><article key={s.id}><div className="source-icon"><BookOpen/></div><div><Status value={s.status}/><h3>{s.title}</h3><p>{s.publisher} · {s.notes}</p><a href={s.url} target="_blank" rel="noreferrer">Open official source <ExternalLink size={14}/></a></div></article>)}</section><div className="download-row"><a href="/data/clay-county-money-trail.json" download><Download size={16}/> Download JSON</a><a href="/data/clay-county-money-trail.csv" download><Download size={16}/> Download CSV</a></div></StandardPage>}
  </div><footer><span>Clay County Money Trail</span><p>Independent civic data project · Neutral, source-first, and incomplete by design until records are verified.</p></footer></main></div>
}
function Kpi({icon,color,label,value,note,muted}:{icon:React.ReactNode;color:string;label:string;value:string;note:string;muted?:boolean}){return <div className="kpi"><div className={`kpi-icon ${color}`}>{icon}</div><span>{label}</span><strong className={muted?'muted-number':''}>{value}</strong><small>{note}</small></div>}
function Disclaimer({title='Budgeted does not mean spent.',text='Budget figures are planned allocations. Actual expenditures will be shown separately when verified records are added.'}:{title?:string;text?:string}){return <div className="disclaimer"><AlertCircle size={19}/><div><strong>{title}</strong><span>{text}</span></div></div>}
function StandardPage({kicker,title,description,children}:{kicker:string;title:string;description:string;children:React.ReactNode}){return <><div className="page-title"><span className="section-kicker">{kicker}</span><h2>{title}</h2><p>{description}</p></div>{children}</>}
type FilterProps={query:string;setQuery:(v:string)=>void;department:string;setDepartment:(v:string)=>void;category:string;setCategory:(v:string)=>void;sourceStatus:string;setSourceStatus:(v:string)=>void;departments:string[];categories:string[]};
function FilterBar(p:FilterProps){return <div className="filter-bar"><label><Search size={16}/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Search records…"/></label><select value={p.department} onChange={e=>p.setDepartment(e.target.value)}>{p.departments.map(v=><option key={v}>{v}</option>)}</select><select value={p.category} onChange={e=>p.setCategory(e.target.value)}>{p.categories.map(v=><option key={v}>{v}</option>)}</select><select value={p.sourceStatus} onChange={e=>p.setSourceStatus(e.target.value)}><option>All source statuses</option><option value="verified_official">Verified official</option><option value="official_estimate">Official estimate</option><option value="derived_estimate">Derived calculation</option><option value="rough_estimate">Rough estimate</option><option value="pending">Not yet populated</option></select></div>}
function Explorer({kind,records:list,expanded,setExpanded,filters}:{kind:'revenue'|'expense';records:RecordItem[];expanded:Record<string,boolean>;setExpanded:(v:Record<string,boolean>)=>void;filters:FilterProps}){const relevant=list.filter(r=>r.flow===kind),groups=Array.from(new Set(relevant.map(r=>r.department))),toggle=(k:string)=>setExpanded({...expanded,[k]:!expanded[k]});return <StandardPage kicker={kind==='revenue'?'REVENUE':'EXPENDITURES'} title={kind==='revenue'?'Where does the money come from?':'Where is the money going?'} description={kind==='revenue'?'Revenue sources, assessments, grants, transfers, and borrowing—separated by status.':'Expandable cost centers with budgeted and actual amounts kept distinct.'}><FilterBar {...filters}/><div className="explorer-layout"><section className="panel tree-panel"><div className="tree-root"><button onClick={()=>toggle(kind)}>{expanded[kind]?<ChevronDown/>:<ChevronRight/>}<span>Clay County · selected fiscal year</span></button><strong>Multiple accounting levels</strong></div>{expanded[kind]&&groups.map(group=>{const items=relevant.filter(r=>r.department===group),key=group.toLowerCase(),total=items.reduce((s,r)=>s+(r.amount??0),0),hasLayers=items.some(r=>r.notes.toLowerCase().includes('do not add')||r.category.includes('Summary'));return <div className="tree-group" key={group}><button onClick={()=>toggle(key)}>{expanded[key]?<ChevronDown/>:<ChevronRight/>}<span>{group}</span><strong>{hasLayers?'Multiple levels':total?money(total):'Not yet populated'}</strong></button>{expanded[key]&&items.map(item=><div className="tree-leaf" key={item.id}><span>{item.name}<Status value={item.sourceStatus}/></span><strong>{money(item.amount)}</strong></div>)}</div>})}</section><section className="panel"><div className="panel-head"><div><span className="section-kicker">RECORDS</span><h3>{relevant.length} matching entries</h3></div></div><RecordsTable records={relevant}/></section></div></StandardPage>}
function RecordsTable({records:rows}:{records:RecordItem[]}){if(!rows.length)return <EmptyState title="No matching records" text="Try clearing a filter, or check back as more official records are added."/>;return <div className="table-wrap"><table><thead><tr><th>Record</th><th>Department</th><th>Type</th><th>Amount</th><th>Source status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.fiscalYear}</small></td><td>{r.department}</td><td><span className="measure">{r.measure}</span></td><td className={r.amount===null?'amount-null':''}>{money(r.amount)}</td><td><Status value={r.sourceStatus}/></td></tr>)}</tbody></table></div>}
